require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bank_billets", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BankBillet. As you add validations to BankBillet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BankBillet.create! valid_attributes
      get bank_billets_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bank_billet = BankBillet.create! valid_attributes
      get bank_billet_url(bank_billet)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bank_billet_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      bank_billet = BankBillet.create! valid_attributes
      get edit_bank_billet_url(bank_billet)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BankBillet" do
        expect {
          post bank_billets_url, params: { bank_billet: valid_attributes }
        }.to change(BankBillet, :count).by(1)
      end

      it "redirects to the created bank_billet" do
        post bank_billets_url, params: { bank_billet: valid_attributes }
        expect(response).to redirect_to(bank_billet_url(BankBillet.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BankBillet" do
        expect {
          post bank_billets_url, params: { bank_billet: invalid_attributes }
        }.to change(BankBillet, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post bank_billets_url, params: { bank_billet: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bank_billet" do
        bank_billet = BankBillet.create! valid_attributes
        patch bank_billet_url(bank_billet), params: { bank_billet: new_attributes }
        bank_billet.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bank_billet" do
        bank_billet = BankBillet.create! valid_attributes
        patch bank_billet_url(bank_billet), params: { bank_billet: new_attributes }
        bank_billet.reload
        expect(response).to redirect_to(bank_billet_url(bank_billet))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        bank_billet = BankBillet.create! valid_attributes
        patch bank_billet_url(bank_billet), params: { bank_billet: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bank_billet" do
      bank_billet = BankBillet.create! valid_attributes
      expect {
        delete bank_billet_url(bank_billet)
      }.to change(BankBillet, :count).by(-1)
    end

    it "redirects to the bank_billets list" do
      bank_billet = BankBillet.create! valid_attributes
      delete bank_billet_url(bank_billet)
      expect(response).to redirect_to(bank_billets_url)
    end
  end
end
